### PR TITLE
Os detect fix

### LINKED ISSUE #43: “This page crashed”
Opening https://containers.github.io/website-new/ shows me

> This page crashed.
> undefined is not an object (evaluating 'e.path')

Happens to me on both Safari and Chrome on macOS, both in the primary session and private browsing. (Did not happen to colleagues testing simultaneously.)

### PR DESCRIPTION
**Pull request by lilyx13**
This should resolve #43

### CODE REVIEW

File: src/components/layout/HeroHeader/index.tsx [hunk 1]
```diff
@@ -14,14 +14,18 @@ type InstallOptionProps = Card & {
...
 
 const detectOperatingSystem = () => {
-  return window.navigator.userAgent
-    .toLowerCase()
-    .split(' ')
-    .find(item => item.includes('linux' || 'windows' || 'macos'));
+  const userAgent = window.navigator.userAgent.toLowerCase().split(' ');
+  if (userAgent.find(item => item.includes('windows'))) {
+    return 'windows';
+  } else if (userAgent.find(item => item.includes('macos'))) {
```
Comment (mtrmac) [inline src/components/layout/HeroHeader/index.tsx:20]: Per the User-Agent values in https://github.com/containers/website-new/issues/43#issuecomment-1534918133 , `macos` is not going to match.
